### ISSUE TITLE
1-word_count.py运行报错

### ISSUE THREAD

**Issue by Edlen-xulun** [pyflink/playgrounds#4]
当我运行：
`docker-compose exec jobmanager ./bin/flink run -py /opt/examples/1-word_count.py`
报错：
`SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
org.apache.flink.client.program.OptimizerPlanEnvironment$ProgramAbortException
	at org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:321)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:205)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:138)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:664)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:213)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:895)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:968)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:968)
`
尝试过将python切换成python3，没有解决问题，有没有人遇到同样错误的？

**Comment by bochuxt** [comment]
This issue was resolved. I noticed the root cause is that docker does not have more disk space.
